services:
  recruitis.api.client:
    class: GuzzleHttp\Client
    arguments:
      $config:
        base_uri: '%env(RECRUITIS_API_BASE_URI)%'
        headers:
          Authorization: 'Bearer %env(RECRUITIS_API_TOKEN)%'

  # NOTE: This is default HTTP Client service.
  GuzzleHttp\ClientInterface: '@recruitis.api.client'
  
  Symfony\Component\Serializer\Serializer:
    arguments:
      - [ '@serializer.normalizer.object' ]
      - [ '@serializer.encoder.json' ]
    tags:
      - { name: serializer.normalizer }

  serializer.normalizer.object:
    class: Symfony\Component\Serializer\Normalizer\ObjectNormalizer
    arguments:
      $nameConverter: '@serializer.name_converter.camel_case_to_snake_case_name_converter'

  serializer.name_converter.camel_case_to_snake_case_name_converter:
    class: Symfony\Component\Serializer\NameConverter\CamelCaseToSnakeCaseNameConverter
