<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerNRWljHJ\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerNRWljHJ/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerNRWljHJ.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerNRWljHJ\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerNRWljHJ\App_KernelDevDebugContainer([
    'container.build_hash' => 'NRWljHJ',
    'container.build_id' => 'fc49b03a',
    'container.build_time' => 1719047489,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerNRWljHJ');
